-- Interval statistics for the service-status page: one row per
-- confirmed-state stretch of a component (ended_at null while ongoing).
-- Days before the cutover keep rendering from service_uptime_day buckets
-- (marked as sampled statistics); new days render from these intervals with
-- coverage, so faster probing never reweights history.

CREATE TABLE service_status_interval (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    component  VARCHAR(64) NOT NULL,
    indicator  VARCHAR(32) NOT NULL,
    started_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    ended_at   TIMESTAMP(6) WITH TIME ZONE,
    source     VARCHAR(32) NOT NULL
);

CREATE INDEX ix_service_status_interval_component_start
    ON service_status_interval (component, started_at);
