/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/catalog": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Browse the public catalog (anonymous access allowed) */
        get: operations["browseCatalog"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/listings/{namespace}/{slug}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Listing detail with visible releases */
        get: operations["getListing"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/listings/{namespace}/{slug}/ratings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Ratings and average score of a listing (anonymous access allowed) */
        get: operations["listRatings"];
        /** Create or update the caller's rating (one per user per listing) */
        put: operations["upsertRating"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/reports": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Report a listing for abuse / policy violation */
        post: operations["reportListing"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/resolutions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Resolve versions and dependency closure for a client environment */
        post: operations["resolve"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/compat/fengyu/claude-marketplace.json": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * CLAUDE-ecosystem marketplace exporting skills and MCP templates as git sources
         * @description Each published SKILL/MCP listing is materialized as a small local git
         *     repository carrying a .claude-plugin/plugin.json (skills paths and an
         *     mcpServers block). Registering this URL as a CLAUDE-type source in the
         *     FengYu host installs skills and disabled MCP server definitions through
         *     the host's existing ecosystem installer; re-cloning picks up updates.
         */
        get: operations["claudeEcosystemMarketplace"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/compat/fengyu/skills-catalog": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** SkillCatalogEntry-compatible skill catalog (fengyu.skills.catalog-url) */
        get: operations["fengyuSkillsCatalog"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/compat/fengyu/fengyu-releases/api/releases/latest": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * GitHub-releases-compatible mirror for the Electron portable updater
         * @description Consumed via the host's updateApiBase setting ({base}/fengyu-releases/api/releases/latest).
         */
        get: operations["fengyuPortableReleaseMirror"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/compat/fengyu/catalog": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * MarketplaceCatalogEntry-compatible plugin catalog for the FengYu host store
         * @description Serves the JSON array contract the FengYu host's built-in FENGYU marketplace
         *     source type fetches, so the host lists, updates and downloads plugins with
         *     zero code changes. Each entry carries the latest published version and a
         *     direct HMAC-ticketed downloadUrl for the package artifact.
         */
        get: operations["fengyuCompatCatalog"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/releases/{releaseId}/download-ticket": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Mint a short-lived, purpose-limited CDN download ticket */
        post: operations["createDownloadTicket"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/updates/app": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Signed app update feed (design §8.4) */
        get: operations["appUpdateFeed"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Register a store account */
        post: operations["register"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Direct email + password login; returns an access token and registers a revocable session */
        post: operations["login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Current authenticated principal */
        get: operations["getCurrentUser"];
        /** Update profile */
        put: operations["updateCurrentUser"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me/password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Change password after re-authenticating with the current one */
        put: operations["changePassword"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me/sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Active sessions and grants */
        get: operations["listSessions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me/sessions/{sessionId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Revoke a session or grant */
        delete: operations["revokeSession"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me/devices": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Registered host devices */
        get: operations["listDevices"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me/devices/{deviceId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Revoke a device (refresh tokens issued to it become invalid immediately) */
        delete: operations["revokeDevice"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me/library": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Favorites, entitlements and install history */
        get: operations["getLibrary"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me/installed": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Installed listings derived from install telemetry (hint, not truth — ADR-009) */
        get: operations["listInstalled"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me/updates": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Installed listings with a newer published release */
        get: operations["listUpdates"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me/favorites/{listingId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Favorite a listing */
        put: operations["addFavorite"];
        post?: never;
        /** Remove a favorite */
        delete: operations["removeFavorite"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/install-events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Report optional, idempotent install telemetry */
        post: operations["reportInstallEvents"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/publisher/listings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Listings owned by the caller's namespaces */
        get: operations["listPublisherListings"];
        put?: never;
        /** Create a listing in a namespace the caller owns */
        post: operations["createListing"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/publisher/listings/{listingId}/releases": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * All releases of a listing including DRAFTs, newest first
         * @description Lets publisher tooling resume an interrupted draft (upload + submit) after a reload. Owner or platform admin only.
         */
        get: operations["listPublisherReleases"];
        put?: never;
        /** Create a draft release */
        post: operations["createRelease"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/publisher/releases/{releaseId}/uploads": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create an upload session; returns a short-lived presigned PUT URL */
        post: operations["createUploadSession"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/publisher/releases/{releaseId}/submit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Submit a release for scanning and review */
        post: operations["submitRelease"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/publisher/releases/{releaseId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Release status including scan findings */
        get: operations["getPublisherRelease"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/publisher/releases/{releaseId}/yank": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Self-withdraw one of the caller's published releases */
        post: operations["yankOwnRelease"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/reviews": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Review queue (REVIEWER or PLATFORM_ADMIN) */
        get: operations["listReviews"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/reviews/{reviewId}/decisions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Record a review decision; APPROVE publishes and platform-signs the envelope */
        post: operations["decideReview"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/releases/{releaseId}/yank": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Yank (soft-withdraw) a published release — PLATFORM_ADMIN */
        post: operations["yankRelease"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/releases/{releaseId}/quarantine": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Quarantine a release on a security event — PLATFORM_ADMIN */
        post: operations["quarantineRelease"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/reports": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Abuse report queue — PLATFORM_ADMIN */
        get: operations["listReports"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/reports/{reportId}/resolution": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Resolve an abuse report — PLATFORM_ADMIN */
        post: operations["resolveReport"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/audit-events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Append-only audit trail reader — PLATFORM_ADMIN */
        get: operations["listAuditEvents"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/upstreams": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Aggregated upstream marketplaces — PLATFORM_ADMIN */
        get: operations["listUpstreams"];
        put?: never;
        /** Register an upstream marketplace (e.g. the official Claude skills) for aggregation */
        post: operations["createUpstream"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/upstreams/{upstreamId}/sync": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Aggregate the upstream now; imported skills run through the full publish pipeline */
        post: operations["syncUpstream"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/organizations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create an organization; reserves the matching namespace */
        post: operations["createOrganization"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/organizations/{organizationId}/webhooks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List organization webhooks */
        get: operations["listWebhooks"];
        put?: never;
        /** Register a webhook for publishing / review / security events */
        post: operations["createWebhook"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/organizations/{organizationId}/members": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List organization members and their roles (membership required) */
        get: operations["listOrgMembers"];
        put?: never;
        /** Add a member by account email — ORG_ADMIN */
        post: operations["addOrgMember"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/organizations/{organizationId}/members/{memberId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Remove a member (the owner cannot be removed) — ORG_ADMIN */
        delete: operations["removeOrgMember"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/organizations/{organizationId}/members/{memberId}/role": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Change a member's role (the owner's role is fixed) — ORG_ADMIN */
        put: operations["changeOrgMemberRole"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/organizations/{organizationId}/audit-events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Audit events touching this organization (membership required) */
        get: operations["listOrgAuditEvents"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @enum {string} */
        ListingType: "APP" | "PLUGIN" | "SKILL" | "MCP" | "FLOW";
        /** @enum {string} */
        Channel: "stable" | "beta" | "alpha" | "nightly" | "private";
        /** @enum {string} */
        Platform: "windows" | "macos" | "linux" | "universal";
        /** @enum {string} */
        Arch: "x64" | "arm64" | "universal";
        /** @enum {string} */
        ArtifactKind: "PACKAGE" | "INSTALLER" | "CHECKSUMS" | "SIGNATURE" | "SBOM";
        Problem: {
            type?: string;
            title?: string;
            status?: number;
            /** @description Stable machine-readable code */
            code?: string;
            detail?: string;
            traceId?: string;
            parameters?: {
                [key: string]: unknown;
            };
        };
        CatalogItem: {
            /** @example infinia://plugin/official/markdown */
            coordinate: string;
            type: components["schemas"]["ListingType"];
            namespace: string;
            slug: string;
            name: string;
            summary?: string;
            category?: string;
            tags?: string[];
            /** Format: uri */
            iconUrl?: string;
            latestVersion?: string;
            channel?: components["schemas"]["Channel"];
            /** Format: int64 */
            downloads?: number;
            publisherName?: string;
            /** Format: date-time */
            updatedAt?: string;
        };
        CatalogPage: {
            items: components["schemas"]["CatalogItem"][];
            nextCursor?: string | null;
            /** Format: int64 */
            totalEstimate?: number;
        };
        Localization: {
            /** @example en */
            locale?: string;
            name?: string;
            summary?: string;
            descriptionMarkdown?: string;
            changelogMarkdown?: string;
        };
        Artifact: {
            artifactId: string;
            kind: components["schemas"]["ArtifactKind"];
            platform: components["schemas"]["Platform"];
            arch: components["schemas"]["Arch"];
            filename: string;
            /** Format: int64 */
            size: number;
            sha256: string;
            keyId?: string;
            mimeType?: string;
        };
        Dependency: {
            coordinate?: string;
            range?: string;
            optional?: boolean;
        };
        Permission: {
            permissionId?: string;
            /** @example network */
            scope?: string;
            required?: boolean;
            reason?: string;
        };
        ListingRelease: {
            releaseId: string;
            version: string;
            status: string;
            channel: components["schemas"]["Channel"];
            /** Format: date-time */
            publishedAt?: string | null;
            /** Format: date-time */
            createdAt?: string;
            requiresHost?: string;
            license?: string;
            sourceUrl?: string;
            changelogMarkdown?: string;
            rolloutPercent?: number;
            artifacts?: components["schemas"]["Artifact"][];
            dependencies?: components["schemas"]["Dependency"][];
            permissions?: components["schemas"]["Permission"][];
        };
        ListingDetail: {
            listingId: string;
            coordinate: string;
            type: components["schemas"]["ListingType"];
            namespace: string;
            slug: string;
            /** @enum {string} */
            visibility?: "PUBLIC" | "UNLISTED" | "PRIVATE";
            status?: string;
            category?: string;
            tags?: string[];
            /** Format: uri */
            iconUrl?: string | null;
            screenshots?: string[];
            defaultChannel?: components["schemas"]["Channel"];
            publisherName?: string;
            /** Format: int64 */
            downloads?: number;
            /** Format: int64 */
            favorites?: number;
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string;
            localizations?: components["schemas"]["Localization"][];
            releases?: components["schemas"]["ListingRelease"][];
        };
        ClientEnvironment: {
            hostVersion: string;
            os: components["schemas"]["Platform"];
            arch: components["schemas"]["Arch"];
            channel?: components["schemas"]["Channel"];
            installed?: {
                coordinate?: string;
                version?: string;
            }[];
        };
        ResolveRequest: {
            /** @example infinia://flow/summer/mail-digest */
            coordinate: string;
            /** @example >=1.0.0 <2.0.0 */
            range?: string;
            client: components["schemas"]["ClientEnvironment"];
        };
        ResolutionItem: {
            coordinate?: string;
            releaseId?: string;
            version?: string;
            channel?: components["schemas"]["Channel"];
            artifacts?: components["schemas"]["Artifact"][];
            permissions?: components["schemas"]["Permission"][];
            requiresHost?: string;
            alreadyInstalled?: boolean;
            reason?: string;
        };
        MissingDependency: {
            coordinate?: string;
            range?: string;
            reason?: string;
        };
        ResolveResponse: {
            resolvable?: boolean;
            rootCoordinate?: string;
            plan?: components["schemas"]["ResolutionItem"][];
            missing?: components["schemas"]["MissingDependency"][];
            /** Format: date-time */
            resolvedAt?: string;
        };
        DownloadTicket: {
            releaseId: string;
            artifactId: string;
            /** Format: uri */
            url: string;
            /** Format: date-time */
            expiresAt?: string;
            sha256: string;
            signature?: string;
            keyId?: string;
            /** Format: int64 */
            size?: number;
        };
        AppUpdateArtifact: {
            /** Format: uri */
            url?: string;
            sha256?: string;
            signature?: string;
            keyId?: string;
            /** Format: int64 */
            size?: number;
            platform?: components["schemas"]["Platform"];
            arch?: components["schemas"]["Arch"];
            kind?: string;
            mimeType?: string;
        };
        AppUpdate: {
            latestVersion?: string | null;
            mandatory?: boolean;
            rollout?: number;
            releaseNotes?: string;
            artifacts?: components["schemas"]["AppUpdateArtifact"][];
            sha256?: string;
            signature?: string;
            keyId?: string;
            /** Format: date-time */
            publishedAt?: string;
            minimumSupportedVersion?: string;
            channel?: components["schemas"]["Channel"];
        };
        RegisterRequest: {
            /** Format: email */
            email: string;
            password: string;
            displayName?: string;
        };
        LoginRequest: {
            /** Format: email */
            email: string;
            password: string;
        };
        LoginResponse: {
            accessToken: string;
            user?: components["schemas"]["PublicUser"];
        };
        PublicUser: {
            userId: string;
            email: string;
            displayName: string;
            roles: string[];
            /** Format: date-time */
            createdAt?: string;
        };
        Session: {
            sessionId?: string;
            clientId?: string;
            kind?: string;
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            lastUsedAt?: string;
            remoteIpHash?: string;
        };
        Device: {
            deviceId?: string;
            publicId?: string;
            name?: string;
            platform?: string;
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            lastSeenAt?: string;
            revoked?: boolean;
        };
        Favorite: {
            listingCoordinate?: string;
            name?: string;
            type?: components["schemas"]["ListingType"];
            latestVersion?: string;
            /** Format: date-time */
            addedAt?: string;
        };
        Entitlement: {
            listingCoordinate?: string;
            free?: boolean;
            /** Format: date-time */
            acquiredAt?: string;
        };
        InstallEvent: {
            idempotencyKey: string;
            coordinate: string;
            version: string;
            type?: components["schemas"]["ListingType"];
            /** @enum {string} */
            action: "install" | "update" | "rollback" | "uninstall";
            /** @enum {string} */
            outcome: "success" | "failure" | "rolled_back";
            hostVersion?: string;
            os?: string;
            arch?: string;
            /** Format: date-time */
            occurredAt?: string;
        };
        Library: {
            favorites?: components["schemas"]["Favorite"][];
            entitlements?: components["schemas"]["Entitlement"][];
            installHistory?: components["schemas"]["InstallEvent"][];
        };
        CreateListingRequest: {
            namespace: string;
            slug: string;
            type: components["schemas"]["ListingType"];
            category?: string;
            tags?: string[];
            defaultChannel?: components["schemas"]["Channel"];
            name: string;
            summary?: string;
            descriptionMarkdown?: string;
            /** @default en */
            locale: string;
        };
        CreateReleaseRequest: {
            /** @example 1.2.0 */
            version: string;
            channel: components["schemas"]["Channel"];
            /** @example >=4.0.0-beta.5 <5.0.0 */
            requiresHost?: string;
            /** @example MIT */
            license?: string;
            /** Format: uri */
            sourceUrl?: string;
            changelogMarkdown?: string;
            dependencies?: components["schemas"]["Dependency"][];
            permissions?: components["schemas"]["Permission"][];
            /** @default 100 */
            rolloutPercent: number;
        };
        UploadSession: {
            uploadId: string;
            releaseId: string;
            filename?: string;
            kind?: components["schemas"]["ArtifactKind"];
            platform?: components["schemas"]["Platform"];
            arch?: components["schemas"]["Arch"];
            /** Format: uri */
            uploadUrl: string;
            /** @enum {string} */
            method: "PUT";
            /** Format: date-time */
            expiresAt?: string;
            /** Format: int64 */
            maxSizeBytes?: number;
        };
        ScanFinding: {
            /** @enum {string} */
            severity?: "INFO" | "WARN" | "ERROR" | "CRITICAL";
            rule?: string;
            message?: string;
        };
        SubmitResult: {
            releaseId?: string;
            status?: string;
            reviewId?: string | null;
            /** Format: date-time */
            submittedAt?: string;
        };
        PublisherRelease: {
            releaseId: string;
            listingCoordinate: string;
            version: string;
            status: string;
            channel: components["schemas"]["Channel"];
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            publishedAt?: string | null;
            findings?: components["schemas"]["ScanFinding"][];
        };
        Review: {
            reviewId: string;
            releaseId: string;
            listingCoordinate?: string;
            listingName?: string;
            version?: string;
            status: string;
            /** Format: date-time */
            submittedAt?: string;
            /** Format: date-time */
            decidedAt?: string | null;
            reviewerId?: string | null;
            notes?: string;
            findings?: components["schemas"]["ScanFinding"][];
        };
        Organization: {
            organizationId?: string;
            slug?: string;
            name?: string;
            /** Format: date-time */
            createdAt?: string;
        };
        Webhook: {
            webhookId?: string;
            organizationId?: string;
            /** Format: uri */
            url?: string;
            events?: string[];
            active?: boolean;
            /** Format: date-time */
            createdAt?: string;
        };
        Rating: {
            ratingId?: string;
            userId?: string;
            stars?: number;
            comment?: string;
            /** Format: date-time */
            updatedAt?: string;
        };
        RatingSummary: {
            /** Format: int64 */
            count?: number;
            average?: number;
        };
        RatingsPage: {
            summary?: components["schemas"]["RatingSummary"];
            ratings?: components["schemas"]["Rating"][];
        };
        UpsertRatingRequest: {
            stars: number;
            comment?: string;
        };
        ReportRequest: {
            /** @example infinia://plugin/official/markdown */
            coordinate: string;
            /** @enum {string} */
            reason: "malware" | "policy_violation" | "spam" | "misleading" | "license" | "other";
            details?: string;
        };
        Report: {
            reportId?: string;
            listingCoordinate?: string;
            listingName?: string;
            reason?: string;
            details?: string;
            /** @enum {string} */
            status?: "OPEN" | "ACTIONED" | "DISMISSED";
            resolutionNote?: string;
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            resolvedAt?: string | null;
        };
        ResolveReportRequest: {
            /** @enum {string} */
            resolution: "ACTIONED" | "DISMISSED";
            note?: string;
        };
        AuditEvent: {
            eventId?: string;
            actorType?: string;
            actorId?: string;
            action?: string;
            resourceType?: string;
            resourceId?: string;
            beforeSummary?: string;
            afterSummary?: string;
            traceId?: string;
            /** Format: date-time */
            occurredAt?: string;
        };
        OrganizationMember: {
            userId?: string;
            email?: string;
            displayName?: string;
            role?: string;
            /** Format: date-time */
            joinedAt?: string;
            owner?: boolean;
        };
        AddMemberRequest: {
            /** Format: email */
            email: string;
            /**
             * @default PUBLISHER
             * @enum {string}
             */
            role: "USER" | "PUBLISHER" | "ORG_ADMIN";
        };
        ChangePasswordRequest: {
            currentPassword: string;
            newPassword: string;
        };
        ChangePasswordResult: {
            succeeded?: boolean;
            message?: string;
        };
        InstalledItem: {
            coordinate?: string;
            version?: string;
            type?: string;
            latestVersion?: string | null;
            latestChannel?: string | null;
            updateAvailable?: boolean;
        };
        Upstream: {
            upstreamId?: string;
            name?: string;
            /** Format: uri */
            marketplaceUrl?: string;
            targetNamespace?: string;
            enabled?: boolean;
            /** Format: date-time */
            lastSyncAt?: string | null;
            lastSyncOk?: boolean | null;
            lastError?: string | null;
        };
        CreateUpstreamRequest: {
            name: string;
            /** Format: uri */
            marketplaceUrl: string;
            targetNamespace: string;
        };
        UpstreamSyncResult: {
            upstream?: string;
            imported?: number;
            skipped?: number;
            failed?: number;
            errors?: string[];
        };
        /** @description Field names mirror the FengYu host's MarketplaceCatalogEntry contract. */
        FengYuCatalogEntry: {
            id?: string;
            name?: string;
            description?: string;
            version?: string;
            author?: string;
            /** Format: uri */
            icon?: string | null;
            category?: string;
            permissions?: string[];
            homepage?: string | null;
            /** @description Direct HMAC-ticketed package URL */
            downloadUrl?: string;
            official?: boolean;
            sha256?: string;
            signature?: string | null;
            keyId?: string | null;
        };
    };
    responses: {
        /** @description Unauthorized */
        ProblemUnauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description Forbidden */
        ProblemForbidden: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description Not found */
        ProblemNotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description Conflict */
        ProblemConflict: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
    };
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    browseCatalog: {
        parameters: {
            query?: {
                type?: components["schemas"]["ListingType"];
                /** @description Free-text search over name */
                query?: string;
                category?: string;
                channel?: components["schemas"]["Channel"];
                /** @description Only listings with a compatible release */
                hostVersion?: string;
                os?: components["schemas"]["Platform"];
                arch?: components["schemas"]["Arch"];
                sort?: "relevance" | "recent" | "downloads" | "favorites";
                cursor?: string;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Catalog page */
            200: {
                headers: {
                    ETag?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CatalogPage"];
                };
            };
        };
    };
    getListing: {
        parameters: {
            query?: {
                channel?: components["schemas"]["Channel"];
            };
            header?: never;
            path: {
                namespace: string;
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Listing detail */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListingDetail"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    listRatings: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                namespace: string;
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Ratings page */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RatingsPage"];
                };
            };
        };
    };
    upsertRating: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                namespace: string;
                slug: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpsertRatingRequest"];
            };
        };
        responses: {
            /** @description Stored rating */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Rating"];
                };
            };
        };
    };
    reportListing: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReportRequest"];
            };
        };
        responses: {
            /** @description Report filed */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Report"];
                };
            };
            409: components["responses"]["ProblemConflict"];
        };
    };
    resolve: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ResolveRequest"];
            };
        };
        responses: {
            /** @description Resolution plan (resolvable=false when dependencies are missing) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResolveResponse"];
                };
            };
        };
    };
    claudeEcosystemMarketplace: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Claude marketplace document */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        plugins?: {
                            name?: string;
                            description?: string;
                            category?: string;
                            keywords?: string[];
                            author?: {
                                name?: string;
                            };
                            source?: {
                                /** @enum {string} */
                                source?: "url";
                                /** @description file:// clone URL */
                                url?: string;
                            };
                        }[];
                    };
                };
            };
        };
    };
    fengyuSkillsCatalog: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Legacy skill catalog entries */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        id?: string;
                        name?: string;
                        description?: string;
                        version?: string;
                        author?: string;
                        downloadUrl?: string;
                        official?: boolean;
                    }[];
                };
            };
        };
    };
    fengyuPortableReleaseMirror: {
        parameters: {
            query?: {
                channel?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description GitHub-compatible release object, or [] when no stable APP release exists */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    fengyuCompatCatalog: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Legacy catalog entries */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FengYuCatalogEntry"][];
                };
            };
        };
    };
    createDownloadTicket: {
        parameters: {
            query?: {
                /** @description Select a specific artifact; defaults to the best platform match */
                artifactId?: string;
            };
            header?: never;
            path: {
                releaseId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Ticket */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DownloadTicket"];
                };
            };
            404: components["responses"]["ProblemNotFound"];
        };
    };
    appUpdateFeed: {
        parameters: {
            query: {
                current: string;
                /** @default stable */
                channel?: components["schemas"]["Channel"];
                os: components["schemas"]["Platform"];
                arch: components["schemas"]["Arch"];
                /** @description Opaque random id used for stable rollout bucketing */
                installId: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Update feed entry; latestVersion=null when up to date */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AppUpdate"];
                };
            };
        };
    };
    register: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterRequest"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PublicUser"];
                };
            };
            409: components["responses"]["ProblemConflict"];
        };
    };
    login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Access token with current user */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LoginResponse"];
                };
            };
            401: components["responses"]["ProblemUnauthorized"];
        };
    };
    getCurrentUser: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Current user */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PublicUser"];
                };
            };
            401: components["responses"]["ProblemUnauthorized"];
        };
    };
    updateCurrentUser: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    displayName?: string;
                };
            };
        };
        responses: {
            /** @description Updated user */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PublicUser"];
                };
            };
        };
    };
    changePassword: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChangePasswordRequest"];
            };
        };
        responses: {
            /** @description Password updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChangePasswordResult"];
                };
            };
            401: components["responses"]["ProblemUnauthorized"];
        };
    };
    listSessions: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Sessions */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Session"][];
                };
            };
        };
    };
    revokeSession: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sessionId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Revoked */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    listDevices: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Devices */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Device"][];
                };
            };
        };
    };
    revokeDevice: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                deviceId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Revoked */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getLibrary: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Library */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Library"];
                };
            };
        };
    };
    listInstalled: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Installed items */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InstalledItem"][];
                };
            };
        };
    };
    listUpdates: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Updatable items */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InstalledItem"][];
                };
            };
        };
    };
    addFavorite: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                listingId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Favorited */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    removeFavorite: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                listingId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Removed */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    reportInstallEvents: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["InstallEvent"][];
            };
        };
        responses: {
            /** @description Accepted */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    listPublisherListings: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Listings */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CatalogItem"][];
                };
            };
        };
    };
    createListing: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateListingRequest"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListingDetail"];
                };
            };
            403: components["responses"]["ProblemForbidden"];
            409: components["responses"]["ProblemConflict"];
        };
    };
    listPublisherReleases: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                listingId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Releases */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PublisherRelease"][];
                };
            };
        };
    };
    createRelease: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                listingId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateReleaseRequest"];
            };
        };
        responses: {
            /** @description Draft release created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PublisherRelease"];
                };
            };
        };
    };
    createUploadSession: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                releaseId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    filename: string;
                    kind: components["schemas"]["ArtifactKind"];
                    platform?: components["schemas"]["Platform"];
                    arch?: components["schemas"]["Arch"];
                    /** Format: int64 */
                    size?: number;
                };
            };
        };
        responses: {
            /** @description Upload session */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UploadSession"];
                };
            };
        };
    };
    submitRelease: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                releaseId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Accepted for scanning */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SubmitResult"];
                };
            };
        };
    };
    getPublisherRelease: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                releaseId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Release */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PublisherRelease"];
                };
            };
        };
    };
    yankOwnRelease: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                releaseId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Yanked */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            403: components["responses"]["ProblemForbidden"];
        };
    };
    listReviews: {
        parameters: {
            query?: {
                status?: "IN_REVIEW" | "APPROVED" | "REJECTED" | "CHANGES_REQUESTED";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Reviews */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Review"][];
                };
            };
        };
    };
    decideReview: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                reviewId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** @enum {string} */
                    decision: "APPROVE" | "REJECT" | "REQUEST_CHANGES";
                    notes?: string;
                };
            };
        };
        responses: {
            /** @description Updated review */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Review"];
                };
            };
        };
    };
    yankRelease: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                releaseId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Yanked */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    quarantineRelease: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                releaseId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Quarantined */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    listReports: {
        parameters: {
            query?: {
                status?: "OPEN" | "ACTIONED" | "DISMISSED";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Reports */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Report"][];
                };
            };
        };
    };
    resolveReport: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                reportId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ResolveReportRequest"];
            };
        };
        responses: {
            /** @description Resolved report */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Report"];
                };
            };
        };
    };
    listAuditEvents: {
        parameters: {
            query?: {
                resourceType?: string;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Audit events (newest first) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuditEvent"][];
                };
            };
        };
    };
    listUpstreams: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Upstream sources */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Upstream"][];
                };
            };
        };
    };
    createUpstream: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateUpstreamRequest"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Upstream"];
                };
            };
        };
    };
    syncUpstream: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                upstreamId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Sync summary */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UpstreamSyncResult"];
                };
            };
        };
    };
    createOrganization: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    slug: string;
                    name: string;
                };
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Organization"];
                };
            };
        };
    };
    listWebhooks: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                organizationId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Webhooks */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Webhook"][];
                };
            };
        };
    };
    createWebhook: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                organizationId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** Format: uri */
                    url: string;
                    /**
                     * @example [
                     *       "release.published",
                     *       "release.quarantined"
                     *     ]
                     */
                    events: string[];
                };
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Webhook"];
                };
            };
        };
    };
    listOrgMembers: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                organizationId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Members */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrganizationMember"][];
                };
            };
        };
    };
    addOrgMember: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                organizationId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AddMemberRequest"];
            };
        };
        responses: {
            /** @description Member added */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrganizationMember"];
                };
            };
        };
    };
    removeOrgMember: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                organizationId: string;
                memberId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Removed */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    changeOrgMemberRole: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                organizationId: string;
                memberId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** @enum {string} */
                    role: "USER" | "PUBLISHER" | "ORG_ADMIN" | "REVIEWER" | "PLATFORM_ADMIN";
                };
            };
        };
        responses: {
            /** @description Updated member */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrganizationMember"];
                };
            };
        };
    };
    listOrgAuditEvents: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                organizationId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Audit events */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuditEvent"][];
                };
            };
        };
    };
}
