-- Interval statistics: one row per confirmed-state stretch of a component
-- (ended_at null while ongoing). Gaps between intervals are unknown time,
-- disclosed by the coverage metric rather than counted as availability.
-- Legacy per-poll buckets in external_uptime_day keep serving days before
-- the cutover; new days render from these intervals.

CREATE TABLE status_interval (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    component  VARCHAR(64) NOT NULL,
    indicator  VARCHAR(32) NOT NULL,
    started_at TIMESTAMP NOT NULL,
    ended_at   TIMESTAMP,
    source     VARCHAR(32) NOT NULL
);

CREATE INDEX idx_status_interval_component_start
    ON status_interval (component, started_at);
